coverage:
  status:
    project:
      default:
        target: 70%
        threshold: 5%
  
#ignore:
  # - "path/to/folder"  # ignore folders and all its contents
  # - "test_*.rb"       # wildcards accepted
  # - "**/*.jl"   
