name = "XGrid"
uuid = "1015158d-cf91-42d0-8ede-00fb4817e22a"
authors = ["Juergen Fuhrmann <juergen.fuhrmann@wias-berlin.de>"]
version = "0.1.3"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Triangulate = "f7e6ffb2-c36d-4f8f-a77e-16e897189344"
